apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: mirror-test-aug26 
  janus-idp.io/tekton: mirror-test-aug26
  backstage.io/kubernetes-id: mirror-test-aug26
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mirror-test-aug26
resources: 
- application-dev.yaml