---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: mirror-test-aug26
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mirror-test-aug26 
  name: mirror-test-aug26
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi