apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mirror-test-aug26
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mirror-test-aug26 
  name: mirror-test-aug26
spec:
  ports:
  - port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app.kubernetes.io/instance: mirror-test-aug26 
